use FootballTournament;

INSERT INTO Trainers VALUES('Виктор','Прокопенко');
INSERT INTO Trainers VALUES('Олег','Базилевич');
INSERT INTO Trainers VALUES('Николай','Павлов');
INSERT INTO Trainers VALUES('Анатолий','Коньков');
INSERT INTO Trainers VALUES('Йожеф','Сабо');
INSERT INTO Trainers VALUES('Валерий','Лобановский');
INSERT INTO Trainers VALUES('Леонид','Буряк');
INSERT INTO Trainers VALUES('Олег','Блохин');
INSERT INTO Trainers VALUES('Алексей','Михайличенко');
INSERT INTO Trainers VALUES('Мирон','Маркевич');
INSERT INTO Trainers VALUES('Даниель','Депо');
INSERT INTO Trainers VALUES('Антуе','Байрон');
INSERT INTO Trainers VALUES('Генадий','Гейне');
INSERT INTO Trainers VALUES('Сергей','Лазюка');
INSERT INTO Trainers VALUES('Дмитрий','Тищенко');
INSERT INTO Trainers VALUES('Вадим','Смирнов');

INSERT INTO Stadions VALUES('НСК "Олимпийский"');
INSERT INTO Stadions VALUES('ОСК "Металлист"');
INSERT INTO Stadions VALUES('"Донбасс-Арена"');
INSERT INTO Stadions VALUES('РСК "Локомотив"');
INSERT INTO Stadions VALUES('"Авангард" г. Луцк');
INSERT INTO Stadions VALUES('"Ворскла" им. Алексея Бутовского');
INSERT INTO Stadions VALUES('"Авангард" г. Ровное');
INSERT INTO Stadions VALUES('ЧС "Чорноморец"');
INSERT INTO Stadions VALUES('"Ильичёвец"');
INSERT INTO Stadions VALUES('"Металург" ');
INSERT INTO Stadions VALUES('"Арена Львов"');
INSERT INTO Stadions VALUES('"Оболонь Арена"');
INSERT INTO Stadions VALUES('Стадион "Металлург"');
INSERT INTO Stadions VALUES('"Днепр"');
INSERT INTO Stadions VALUES('УТК им. Банникова');
INSERT INTO Stadions VALUES('КСК "Ника"');

INSERT INTO Teams VALUES('Динамо К',1,8);
INSERT INTO Teams VALUES('Металлист',2,4);
INSERT INTO Teams VALUES('Таврия',4,3);
INSERT INTO Teams VALUES('Заря',7,2);
INSERT INTO Teams VALUES('Арсенал К',16,5);
INSERT INTO Teams VALUES('Ильичёвец',9,7);
INSERT INTO Teams VALUES('Оболонь',12,6);
INSERT INTO Teams VALUES('Карпаты',11,1);
INSERT INTO Teams VALUES('Шахтёр',3,9);
INSERT INTO Teams VALUES('Волынь',5,11);
INSERT INTO Teams VALUES('Ворскла',6,10);
INSERT INTO Teams VALUES('Кривбасс',10,14);
INSERT INTO Teams VALUES('Черноморец',8,12);
INSERT INTO Teams VALUES('ПФК Александрия',15,13);
INSERT INTO Teams VALUES('Днепр Дн',14,16);
INSERT INTO Teams VALUES('Металлург Д',13,15);

INSERT INTO Players VALUES('Александр','Алиев',18,0,1);
INSERT INTO Players VALUES('Сергей','Кандауров',28,0,1);
INSERT INTO Players VALUES('Андрей','Анненков',28,0,1);
INSERT INTO Players VALUES('Алексей','Антонов',25,0,1);
INSERT INTO Players VALUES('Александр','Шовковский',34,1,1);
INSERT INTO Players VALUES('Аоексей','Антюхин',19,0,2);
INSERT INTO Players VALUES('Сергей','Ателькин',20,0,2);
INSERT INTO Players VALUES('Константин','Балабанов',24,0,2);
INSERT INTO Players VALUES('Алексей','Бахарев',24,0,2);
INSERT INTO Players VALUES('Андрей','Дыкань',25,1,2);
INSERT INTO Players VALUES('Сергей','Беженар',28,0,3);
INSERT INTO Players VALUES('Роман','Безус',26,0,3);
INSERT INTO Players VALUES('Алексей','Белик',32,0,3);
INSERT INTO Players VALUES('Руслан','Бидненко',34,0,3);
INSERT INTO Players VALUES('Андрей','Пятов',29,1,3);
INSERT INTO Players VALUES('Игорь','Богуш',30,0,4);
INSERT INTO Players VALUES('Ярослав','Бондаренко',24,0,4);
INSERT INTO Players VALUES('Андрей','Букель',25,0,4);
INSERT INTO Players VALUES('Сергей','Валяев',26,0,4);
INSERT INTO Players VALUES('Александр','Рыбка',37,1,4);
INSERT INTO Players VALUES('Максим','Василитчук',25,0,5);
INSERT INTO Players VALUES('Евгений','Ватаманюк',31,0,5);
INSERT INTO Players VALUES('Артемий','Ващук',21,0,5);
INSERT INTO Players VALUES('Дмитрий','Венглинский',20,0,5);
INSERT INTO Players VALUES('Максим','Коваль',30,1,5);
INSERT INTO Players VALUES('Марат','Вирт',24,0,6);
INSERT INTO Players VALUES('Андрей','Воробей',25,0,6);
INSERT INTO Players VALUES('Игорь','Гай',36,0,6);
INSERT INTO Players VALUES('Герасим','Гайдаш',35,0,6);
INSERT INTO Players VALUES('Александр','Горяинов',30,1,6);
INSERT INTO Players VALUES('Роман','Галовский',25,0,7);
INSERT INTO Players VALUES('Сергей','Гецко',28,0,7);
INSERT INTO Players VALUES('Александр','Гладкий',28,0,7);
INSERT INTO Players VALUES('Александр','Горшков',17,0,7);
INSERT INTO Players VALUES('Сергей','Долганский',18,1,7);
INSERT INTO Players VALUES('Армен','Грицай',25,0,8);
INSERT INTO Players VALUES('Виктор','Гудименко',21,0,8);
INSERT INTO Players VALUES('Олег','Гусев',19,0,8);
INSERT INTO Players VALUES('Валентин','Гусин',28,0,8);
INSERT INTO Players VALUES('Сергей','Перхун',39,1,8);
INSERT INTO Players VALUES('Сергей','Дирявка',28,0,9);
INSERT INTO Players VALUES('Юрий','Дмитрулин',21,0,9);
INSERT INTO Players VALUES('Евгений','Драгунов',31,0,9);
INSERT INTO Players VALUES('Юрий','Дудник',36,0,9);
INSERT INTO Players VALUES('Виктор','Чанов',33,1,9);
INSERT INTO Players VALUES('Игорь','Жабченко',18,0,10);
INSERT INTO Players VALUES('Сергей','Задорожный',21,0,10);
INSERT INTO Players VALUES('Сергей','Закарлюка',28,0,10);
INSERT INTO Players VALUES('Роман','Зозуля',39,0,10);
INSERT INTO Players VALUES('Юрий','Дегтерев',22,1,10);
INSERT INTO Players VALUES('Денис','Олейник',32,0,11);
INSERT INTO Players VALUES('Геннадий','Онищенко',23,0,11);
INSERT INTO Players VALUES('Александр','Назаренко',24,0,11);
INSERT INTO Players VALUES('Виктор','Несмачный',28,0,11);
INSERT INTO Players VALUES('Виталий','Рева',29,1,11);
INSERT INTO Players VALUES('Юрий','Никифоров',28,0,12);
INSERT INTO Players VALUES('Денис','Мущинка',27,0,12);
INSERT INTO Players VALUES('Юрий','Мусолитин',22,0,12);
INSERT INTO Players VALUES('Геннадий','Морозюк',33,0,12);
INSERT INTO Players VALUES('Евгений','Рудаков',28,1,12);
INSERT INTO Players VALUES('Виктор','Левицкий',19,0,13);
INSERT INTO Players VALUES('Сергей','Леженцев',28,0,13);
INSERT INTO Players VALUES('Александр','Лисицкий',34,0,13);
INSERT INTO Players VALUES('Денис','Лужный',28,0,13);
INSERT INTO Players VALUES('Дмитрий','Шутков',22,1,13);
INSERT INTO Players VALUES('Николай','Луценко',22,0,14);
INSERT INTO Players VALUES('Сергей','Третьяк',22,0,14);
INSERT INTO Players VALUES('Юрий','Топчиев',25,0,14);
INSERT INTO Players VALUES('Анатолий','Тимощук',28,0,14);
INSERT INTO Players VALUES('Илья','Близнюк',27,1,14);
INSERT INTO Players VALUES('Геннадий','Телесненко',26,0,15);
INSERT INTO Players VALUES('Виктор','Суслов',25,0,15);
INSERT INTO Players VALUES('Александр','Степаненко',28,0,15);
INSERT INTO Players VALUES('Юрий','Старостяк',32,0,15);
INSERT INTO Players VALUES('Александр','Ткаченко',35,1,15);
INSERT INTO Players VALUES('Александр','Слюсар',30,0,16);
INSERT INTO Players VALUES('Юрий','Скрипник',28,0,16);
INSERT INTO Players VALUES('Олег','Симоненко',28,0,16);
INSERT INTO Players VALUES('Олег','Серебренников',22,0,16);
INSERT INTO Players VALUES('Николай','Медин',20,1,16);